language: php

arch:
    - amd64
    - arm64
php:
  - hhvm

before_script:
  - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source --dev install

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml
